### ISSUE TITLE
Json status

### ISSUE THREAD

**Issue by Liz4v** [abando/esupa#1]
Have a way to provide the capacity occupation status from an outside site. Proposed format:

URL: /event_slug/json/state

```
{"exists": true,
 "id": 1, "slug": "abando9",
 "subs_open": true,
 "currently_available": 10,
 "potentially_available": 15}

{"exists": true,
 "id": 1, "slug": "abando9",
 "subs_open": true,
 "currently_available": "over 20",
 "potentially_available": "over 20"}

{"exists": true,
 "id": 2, "slug": "abando10",
 "subs_open": false}

{"exists": false,
 "slug": "does not exist"}
```

The upper bound is configurable from the event edit screen from Django admin panel.

**Comment by dorival** [comment]
The format seems okay.  Although I think smallCamelCase is the best for JSON properties. Should we also consider using the word "Registration" as opposed to "Subscription"? The second one hints towards something like a mailing list, and Registration is more "registering to an event".

Second but not very important, is to display a standard sign beside the number to indicate exact or "over". If "+", then it's over 20. If + absent, exact 14. If a developer decides to print the number as is, it works just fine in any idiom, or else, he can just check for a trailing + to apply a better i18n string.

```
{
"exists": true,
"id": 1, 
"slug": "abando9",
"registrationOpen": true,
"currentlyAvailable": "14",
"potentiallyAvailable": "20+"
}
```

If not found, slug should be empty to avoid reusing an information prop for another reason. Create another prop for that:

```
{ "exists": false,  "slug": "", errorMessage: "Event does not exist." }
```

**Comment by Liz4v** [comment]
On Staging.
